### PR TITLE
Name change

### PR DESCRIPTION
**Pull request by mathersrob**
I've wondering why the latest version of a package (v0.1.3.4) on github (https://github.com/TheHydrophobicityProject/HydrophobicityExplorer) has updated on [pypi.org](http://pypi.org/) (https://pypi.org/project/mhp/) but not on conda-forge (https://anaconda.org/scohenjanes/mhp). Perhaps, the url in [setup.py](http://setup.py/) needs updated to reflect the name change?

### CODE REVIEW

**Comment by mathersrob** [comment]
The last update on https://anaconda.org/scohenjanes/mhp/files occurred on 0ctober 18, 2022. Then, the name changed from mhp to Hydrophobicity Explorer on October 31, 2022. Since then, updates are not occurring. I'm going to change the url in [setup.py](http://setup.py/) and see if that helps.

**Comment by jdpadrnos** [comment]
It's actually not to do with the name--updates for pip and conda are handled a little differently, and there's currently an issue with building the Conda package.

I think updates to the pip package are handled manually by Sander running pypi_publish.sh using his credentials.

There's a GitHub Action configured to update the Conda package but it is set to run only on every GitHub release version (a good 
idea to avoid updating the package on every commit), and we haven't published any GitHub release versions so it has never run.

I'm pretty sure the reason Sander hasn't run a release manually like he did for the pip package is the issues he described in #13 with the build taking a ridiculously long time and installing conflicting versions of packages--even if we can run the packaging workflow, we really don't want those kinds of issues making it into a released version.

**Comment by scohenjanes5** [comment]
It would be good to let GitHub actions handle this for us, because I don't imagine many major packages do manual packaging the way I have (though it's what all the tutorials I've seen use 😀)

I just opened another PR #15 that changed the build recipe for conda significantly. In short, the dependencies are no longer bundled in with our package. This reduces the file size from ~100 MB to ~30 kB. Strangely, it does not reduce the build time, but at least I was able to get the output package to work when installing the `tar.bz2` file directly, and by installing from the `scohenjanes` channel on anaconda.

**Comment by scohenjanes5** [comment]
Also @mathersrob because the main branch was so many commits ahead of the name change branch, I updated it from the current main branch, so the merge can be completed without conflicts.

This would just cause the current PR I have open #15 to have conflicts, but that can be dealt with easily enough.

**Comment by scohenjanes5** [comment]
> I updated it from the current main branch, so the merge can be completed without conflicts.

Upon review, I accepted the wrong changes for certain files so I am currently correcting that.

**Review by scohenjanes5 — APPROVED** [review]
After making some changes necessary because of conflicts with the main branch, this is ready to merge.

**Pull request merged**
